### ISSUE TITLE
(OSC3) Selecting Chords mode crashes [Win 10, Rack v2.11 Pro]

### ISSUE THREAD

**Issue by SteveRussell33** [liquidcitymotors/Via-for-VCVRack#38]
Clicking BEAT button twice (i.e. selecting Chords mode) produces segmentation fault.

```
Thread 34 received signal SIGSEGV, Segmentation fault.
[Switching to Thread 8584.0x2564]
0x00007ff9681a73ee in ViaOsc3::updateBaseFreqsSmooth (this=0x2c8ebdff0c0) at ./Via/modules/inc/osc3.hpp:484
484                             int32_t chordMultiplier = scale[64 + intervals[14 + chords[chord*2 + 1]]] << 5;
(gdb) bt
#0  0x00007ff9681a73ee in ViaOsc3::updateBaseFreqsSmooth (this=0x2c8ebdff0c0) at ./Via/modules/inc/osc3.hpp:484
#1  0x00007ff9680f502f in ViaOsc3::slowConversionCallback (this=0x2c8ebdff0c0) at ./Via/modules/inc/osc3.hpp:716
#2  Osc3::process (args=..., this=0x2c8ebdfe8d0) at src/osc3.cpp:509
#3  Osc3::process (this=0x2c8ebdfe8d0, args=...) at src/osc3.cpp:497
#4  0x00007ff977e4647a in libRack!_ZN4rack6engine6Module9doProcessERKNS1_11ProcessArgsE () from /c/Program Files/VCV/Rack2 Pro/libRack.dll
#5  0x00007ff977e40691 in libRack!_ZN4rack6engine12EngineWorker3runEv () from /c/Program Files/VCV/Rack2 Pro/libRack.dll
#6  0x00007ff992fd1371 in ?? () from /c/Program Files/VCV/Rack2 Pro/libstdc++-6.dll
#7  0x00007ff99a2e4d53 in ?? () from /c/Program Files/VCV/Rack2 Pro/libwinpthread-1.dll
#8  0x00007ff9a962af5a in msvcrt!_beginthreadex () from /c/WINDOWS/System32/msvcrt.dll
#9  0x00007ff9a962b02c in msvcrt!_endthreadex () from /c/WINDOWS/System32/msvcrt.dll
#10 0x00007ff9a9887034 in KERNEL32!BaseThreadInitThunk () from /c/WINDOWS/System32/KERNEL32.DLL
#11 0x00007ff9aaf02651 in ntdll!RtlUserThreadStart () from /c/WINDOWS/SYSTEM32/ntdll.dll
#12 0x0000000000000000 in ?? ()
```

**Comment by liquidcitymotors** [comment]
Yikes! Thank you so much for the heads up on this as well as issue #39 👀

Fortunately, I just got my hands on a Windows machine so I should be able to get this sorted out. 

When I tested on Mac just now, I found that it didn't segfault but also that the detune knob was ranged incorrectly for this particular mode (chords but no quantization) and I suspect these things are related.

I'll follow up here once I think I've got a fix.

**Comment by SteveRussell33** [comment]
Still crashes:
```
Thread 42 received signal SIGSEGV, Segmentation fault.
[Switching to Thread 2492.0x104c]
0x00007ffe979373ee in ViaOsc3::updateBaseFreqsSmooth (this=0x1b8a6d2ec30) at ./Via/modules/inc/osc3.hpp:491
491                             int32_t chordMultiplier = scale[64 + intervals[12 + chords[chord*2 + 1]]] << 5;
(gdb) bt
#0  0x00007ffe979373ee in ViaOsc3::updateBaseFreqsSmooth (this=0x1b8a6d2ec30) at ./Via/modules/inc/osc3.hpp:491
#1  0x00007ffe9788502f in ViaOsc3::slowConversionCallback (this=0x1b8a6d2ec30) at ./Via/modules/inc/osc3.hpp:723
#2  Osc3::process (args=..., this=0x1b8a6d2e440) at src/osc3.cpp:509
#3  Osc3::process (this=0x1b8a6d2e440, args=...) at src/osc3.cpp:497
#4  0x00007ffea682647a in libRack!_ZN4rack6engine6Module9doProcessERKNS1_11ProcessArgsE () from /c/Program Files/VCV/Rack2 Pro/libRack.dll
#5  0x00007ffea68214f2 in libRack!_ZN4rack6engine6Engine9stepBlockEi () from /c/Program Files/VCV/Rack2 Pro/libRack.dll
#6  0x00007ffea67af3ce in libRack!_ZN4rack5audio6Device13processBufferEPKfiPfii () from /c/Program Files/VCV/Rack2 Pro/libRack.dll
#7  0x00007ffea6c7e8c0 in libRack!_ZN4rack13RtAudioDevice15rtAudioCallbackEPvS1_jdjS1_ () from /c/Program Files/VCV/Rack2 Pro/libRack.dll
#8  0x00007ffea6c48ee0 in libRack!_ZN11RtApiWasapi12wasapiThreadEv () from /c/Program Files/VCV/Rack2 Pro/libRack.dll
#9  0x00007ffea6c4a9fe in libRack!_ZN11RtApiWasapi15runWasapiThreadEPv () from /c/Program Files/VCV/Rack2 Pro/libRack.dll
#10 0x00007ffed9f07034 in KERNEL32!BaseThreadInitThunk () from /c/WINDOWS/System32/KERNEL32.DLL
#11 0x00007ffeda282651 in ntdll!RtlUserThreadStart () from /c/WINDOWS/SYSTEM32/ntdll.dll
#12 0x0000000000000000 in ?? ()
```

**Comment by liquidcitymotors** [comment]
Hey @SteveRussell33, looks like I needed to take a bit of a vacation before I was ready to tackle this

**Comment by liquidcitymotors** [comment]
Hey @SteveRussell33, looks like I needed a bit of a vacation before I was able to tackle this.

I'm trying to recreate these bugs with a fresh clone of Via for Rack at 59c1e9037d2ffb107fc8015d8fb1bd63c2b280ca and Rack Free 2.1.2 but I'm not experiencing the issue.

I'll keep poking around, but do you still have these issues with the latest commit and the latest version of Rack?

**Comment by liquidcitymotors** [comment]
Scratch that, seems like the problem does in fact come up in debug mode

**Comment by liquidcitymotors** [comment]
Hey @SteveRussell33 I found and fixed a major problem with the osc3 scale file load, turns out that things were completely borked with that on Windows. Could you give the latest commit a try when you get the chance?

**Comment by SteveRussell33** [comment]
All good here Will! No crashes, file load is good. Looks like the vacation done you good ;)

I'll do some more testing and will probably close both issues in a day or two.
