### ISSUE TITLE
(OSC3) Selecting Semitone Quantization mode crashes [Win 10, Rack v2.11 Pro]

### ISSUE THREAD

**Issue by SteveRussell33** [liquidcitymotors/Via-for-VCVRack#39]
```
Thread 38 received signal SIGSEGV, Segmentation fault.
[Switching to Thread 7548.0x774]
0x00007ff967956e9c in ViaOsc3::updateBaseFreqsScale (this=0x1a9b68ecd00) at ./Via/modules/inc/osc3.hpp:390
390                                             expo.convert(offset << 5) >> 2);
(gdb) bt
#0  0x00007ff967956e9c in ViaOsc3::updateBaseFreqsScale (this=0x1a9b68ecd00) at ./Via/modules/inc/osc3.hpp:390
#1  0x00007ff9678a502f in ViaOsc3::slowConversionCallback (this=0x1a9b68ecd00) at ./Via/modules/inc/osc3.hpp:716
#2  Osc3::process (args=..., this=0x1a9b68ec510) at src/osc3.cpp:509
#3  Osc3::process (this=0x1a9b68ec510, args=...) at src/osc3.cpp:497
#4  0x00007ff977e4647a in libRack!_ZN4rack6engine6Module9doProcessERKNS1_11ProcessArgsE () from /c/Program Files/VCV/Rack2 Pro/libRack.dll
#5  0x00007ff977e40691 in libRack!_ZN4rack6engine12EngineWorker3runEv () from /c/Program Files/VCV/Rack2 Pro/libRack.dll
#6  0x00007ff987c81371 in ?? () from /c/Program Files/VCV/Rack2 Pro/libstdc++-6.dll
#7  0x00007ff99a2a4d53 in ?? () from /c/Program Files/VCV/Rack2 Pro/libwinpthread-1.dll
#8  0x00007ff9a962af5a in msvcrt!_beginthreadex () from /c/WINDOWS/System32/msvcrt.dll
#9  0x00007ff9a962b02c in msvcrt!_endthreadex () from /c/WINDOWS/System32/msvcrt.dll
#10 0x00007ff9a9887034 in KERNEL32!BaseThreadInitThunk () from /c/WINDOWS/System32/KERNEL32.DLL
#11 0x00007ff9aaf02651 in ntdll!RtlUserThreadStart () from /c/WINDOWS/SYSTEM32/ntdll.dll
#12 0x0000000000000000 in ?? ()
```

**Comment by SteveRussell33** [comment]
Still crashes:
```
Thread 43 received signal SIGSEGV, Segmentation fault.
[Switching to Thread 6168.0xa28]
0x00007ffe97976e9c in ViaOsc3::updateBaseFreqsScale (this=0x1ff3c1f2ed0) at ./Via/modules/inc/osc3.hpp:397
397                                             expo.convert(offset << 5) >> 2);
(gdb) bt
#0  0x00007ffe97976e9c in ViaOsc3::updateBaseFreqsScale (this=0x1ff3c1f2ed0) at ./Via/modules/inc/osc3.hpp:397
#1  0x00007ffe978c502f in ViaOsc3::slowConversionCallback (this=0x1ff3c1f2ed0) at ./Via/modules/inc/osc3.hpp:723
#2  Osc3::process (args=..., this=0x1ff3c1f26e0) at src/osc3.cpp:509
#3  Osc3::process (this=0x1ff3c1f26e0, args=...) at src/osc3.cpp:497
#4  0x00007ffea682647a in libRack!_ZN4rack6engine6Module9doProcessERKNS1_11ProcessArgsE () from /c/Program Files/VCV/Rack2 Pro/libRack.dll
#5  0x00007ffea68214f2 in libRack!_ZN4rack6engine6Engine9stepBlockEi () from /c/Program Files/VCV/Rack2 Pro/libRack.dll
#6  0x00007ffea67af3ce in libRack!_ZN4rack5audio6Device13processBufferEPKfiPfii () from /c/Program Files/VCV/Rack2 Pro/libRack.dll
#7  0x00007ffea6c7e8c0 in libRack!_ZN4rack13RtAudioDevice15rtAudioCallbackEPvS1_jdjS1_ () from /c/Program Files/VCV/Rack2 Pro/libRack.dll
#8  0x00007ffea6c48ee0 in libRack!_ZN11RtApiWasapi12wasapiThreadEv () from /c/Program Files/VCV/Rack2 Pro/libRack.dll
#9  0x00007ffea6c4a9fe in libRack!_ZN11RtApiWasapi15runWasapiThreadEPv () from /c/Program Files/VCV/Rack2 Pro/libRack.dll
#10 0x00007ffed9f07034 in KERNEL32!BaseThreadInitThunk () from /c/WINDOWS/System32/KERNEL32.DLL
#11 0x00007ffeda282651 in ntdll!RtlUserThreadStart () from /c/WINDOWS/SYSTEM32/ntdll.dll
#12 0x0000000000000000 in ?? ()
```

**Comment by liquidcitymotors** [comment]
Unfortunately I found the same when I tested this over on Windows and I had to give up for the night, looking forward to taking another shot at this once I finish up the day job. Thanks so much for your help!

**Comment by SteveRussell33** [comment]
No problem Will!
